### PR TITLE
[WIP] Add join messages module

### PR DESCRIPTION
**Pull request by tadeokondrak**

### CODE REVIEW

**Comment by ldelelis** [comment]
What's missing here is handling the `events` export right?

**Comment by tadeokondrak** [comment]
That's what's blocking this, but the set join message isn't done yet either.

**Comment by ldelelis** [comment]
Copying the event loader snippet here before it gets buried in chat any further and we all forget about it:

```diff
--- a/scepter.js
+++ b/scepter.js
@@ -41,6 +41,11 @@ const loadedModules = {}
 
 const loadModule = name => {
   const module = require(`./modules/${name}`)
+  if (module.events != null) {
+    for (let event of module.events) {
+      client.on(event.trigger, event.run)
+    }
+  }
   loadedModules[name] = module
 }
```

**Comment by ldelelis** [comment]
[Patch with the rewritten typescript module](https://github.com/nixnest/scepter/files/2719641/typescript.txt)

**Comment by ldelelis** [comment]
This is now unblocked right? #20 added event handling.

**Pull request closed without merging**
